meta-integrity/conf/layer.conf: add opemembedded-layer as layer dependency
Fix ima-inspect build failure:

$ bitbake ima-inspect
ERROR: Nothing PROVIDES 'tclap' (but
/build/poky/meta-secure-core/meta-integrity/recipes-support/ima-inspect/ima-inspect_0.11.bb
DEPENDS on or otherwise requires it).
ERROR: Required build target 'ima-inspect' has no buildable providers.
Missing or unbuildable dependency chain was: ['ima-inspect', 'tclap']

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>