linux-yocto*: fix require of include file
There exists only linux-yocto-tpm2.inc. BPN will resolve to
linux-yocto-rt and linux-yocto-dev which don't have a recipe specific
include files.

Fixes bitbake recipe parsing errors like:

ERROR: ParseError at
/home/builder/src/build/../meta-secure-core/meta-tpm2/recipes-kernel/linux/linux-yocto-rt_5.%.bbappend:1:
Could not include required file linux-yocto-rt-tpm2.inc
ERROR: Parsing halted due to errors, see error messages above

Signed-off-by: Mikko Rapeli <mikko.rapeli@linaro.org>