sbsigntool: Fix for target build
* Remove unnecessary inherit native
This is a target recipe, the "inherit native" is not needed, the
sbsigntool-native is extended by BBCLASSEXTEND which is already present.

Fixed when multilib is enabled:
$ bitbake lib32-sbsigntool
ERROR: Nothing PROVIDES 'lib32-sbsigntool'.

* Add util-linux-libuuid to DEPENDS since it is required by target build

* Add read_write_all.c to common_SOURCES to fix build errors.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>