meta-encrypted-storage: check luks DISTRO_FEATURES
Fix the yocto compliance issue:
  INFO: test_signatures (common.CommonCheckLayer)
  INFO:  ... FAIL

  Stdout:
  Loaded 2790 entries from dependency cache.
  INFO: Traceback (most recent call last):
  File "/build/layers/oe-core/scripts/lib/checklayer/cases/common.py", line 81, in test_signatures
    self.fail('Adding layer %s changed signatures.\n%s' % (self.tc.layer['name'], msg))
AssertionError: Adding layer meta-encrypted-storage changed signatures.
208 signatures changed, initial differences (first hash before, second after):
    cryptsetup:do_package: f0fa7d14534fb27c9caf639036338bbfa270ac29524b30d699f8f8ea0ec8cb02 -> 35d3ffd44373fc052d5bf7c0b1e649b585e49638ddc21109651e9602786aa87b
      bitbake-diffsigs --task cryptsetup do_package --signature f0fa7d14534fb27c9caf639036338bbfa270ac29524b30d699f8f8ea0ec8cb02 35d3ffd44373fc052d5bf7c0b1e649b585e49638ddc21109651e9602786aa87b
      NOTE: Starting bitbake server...
      basehash changed from 69f1e7096d59cdc20c48b2c7591a3d5c5abbdcf4452c2a2dbdd84ed352054477 to e8cb4b995a71a2b37597a4cdd37b91fe2904895db51922664d2ac2ae1702aecc
      Variable RDEPENDS:cryptsetup value changed:
      "     libdevmapper  {+lvm2+} udev lvm2-udevrules"
      Variable RRECOMMENDS:cryptsetup value changed:
      "     kernel-module-aes-generic     kernel-module-dm-crypt     kernel-module-md5     kernel-module-cbc     kernel-module-sha256-generic     kernel-module-xts  {+lvm2-udevrules+}"

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>