meta: create README symbolic link
Run yocto-check-layer to check layer compliance of Yocto will report the
following error:

$ yocto-check-layer ../meta-secure-core/meta
INFO: Detected layers:
[snip]
INFO: test_readme (common.CommonCheckLayer)
INFO:  ... FAIL
INFO: Traceback (most recent call last):
  File "/buildarea/poky/scripts/lib/checklayer/cases/common.py", line 15, in test_readme
    msg="Layer doesn't contains README file.")
AssertionError: False is not true : Layer doesn't contains README file.
[snip]

There is no need to create a new README for this layer. We just create a
symbolic link of README from the top-level.

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>